# Generated by Django 4.0.3 on 2022-03-25 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=14)),
                ('private', models.DecimalField(decimal_places=2, max_digits=5)),
                ('incompleto', models.DecimalField(decimal_places=2, max_digits=5)),
                ('data_da_ultima_compra', models.DateField()),
                ('ticket_medio', models.FloatField()),
                ('ticket_da_ultima_compra', models.FloatField()),
                ('loja_mais_frequente', models.CharField(max_length=18)),
                ('loja_da_ultima_compra', models.CharField(max_length=18)),
            ],
        ),
    ]
